version: '3'

services:
  backend:
    build:
      context: ./backend  # Assuming the backend Dockerfile is in a folder named 'backend'
      dockerfile: Dockerfile
    container_name: flask_backend
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development  # Or production depending on your setup
    volumes:
      - ./backend:/app  # Optional: sync local code with container for live changes
    networks:
      - app_network

  frontend:
    build:
      context: ./frontend  # Assuming the frontend Dockerfile is in a folder named 'frontend'
      dockerfile: Dockerfile
    container_name: react_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app  # Optional: sync local code with container for live changes
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
